### ISSUE TITLE
Controlled values seems buggy

### ISSUE THREAD

**Issue by Guarn** [Ali-Azmoud/flutter_xlider#62]
Hey, great works overall, I just have a problem while controlling the **values** on a rangeSlider.

Lets take the following example (simple Flutter new and add your widget :

```
class _MyHomePageState extends State<MyHomePage> {
   List<double> data = [5.0, 15.0];
  double min = 5.0;
  double max = 15.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: MediaQuery.of(context).size.height,
        child: Center(
            child: FlutterSlider(
          onDragging: (x, begin, end) {
            setState(() {
              data[0] = begin;
              data[1] = end;
            });
          },
          values: data,
          rangeSlider: true,
          max: max,
          min: min,
        )),
      ),
      floatingActionButton: Container(
          color: Colors.blue[100],
          child: IconButton(
            icon: Icon(Icons.replay),
            onPressed: () {
              setState(() {
                data = [min, max];
              });
            },
          )),
    );
  }
}
```

The **values** of my slider is controlled by **data**. I've put a reset button to restore initial values. 

But the **reset** seems buggy. Sometimes, it works, then I full reload, it doesn't work anymore (cursors stays static).

This is happening only if the reset value is the same as the **min** and **max**.
If I choose to reset like that :

```
onPressed: () {
              setState(() {
                data = [min, 14.0];
              });
            },
```
it works perfectly.

**Comment by Ali-Azmoud** [comment]
Hi
which version are you using? I've tested your code and it works well.

**Comment by Guarn** [comment]
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_xlider: 3.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

I'll try with 3.3.1
